aws_rds_postgres: &aws_rds_postgres
  host: "${AWS_RDS_HOST}"
  name: "${AWS_RDS_DB_NAME}"
  user: "${AWS_RDS_USER}"
  password: "${AWS_RDS_PASSWORD}"
  port: 5432

metaflow-service:
  metadatadb: *aws_rds_postgres

metaflow-ui:
  uiBackend:
    metadatadb: *aws_rds_postgres
