aws_rds_postgres: &aws_rds_postgres
  host: "rds-instance-endpoint.amazonaws.com"
  name: "metaflow_db"
  user: "metaflow_admin"
  password: "password"
  port: 5432

metaflow-service:
  metadatadb: *aws_rds_postgres

metaflow-ui:
  uiBackend:
    metadatadb: *aws_rds_postgres
